apiVersion: v1
kind: Service
metadata:
  name: rag-langchain-frontend
  namespace: rag-yeni
  annotations:
    cloud.google.com/backend-config: '{"default": "rag-langchain-frontend-backend"}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: rag-langchain-frontend
spec:
  type: ClusterIP
  selector:
    app: rag-langchain-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
