apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: rag-langchain-frontend
  namespace: rag-langchain
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
