apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-langchain
  namespace: rag-yeni
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: rag-langchain-cert
    networking.gke.io/v1beta1.FrontendConfig: rag-langchain-frontend
spec:
  rules:
    - host: chat.mammas.studio
      http:
        paths:
          - path: /ask
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /suggestions
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /feedback
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /workspace
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /originals
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /documents
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: rag-langchain
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-langchain-frontend
                port:
                  number: 80
