apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - model-cache-pvc.yaml
  - redis-pvc.yaml
  - data-pvc.yaml
  - redis.yaml
  - postgres.yaml
  - kafka.yaml
  - backendconfig.yaml
  - managed-certificate.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
