apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qdrant-pvc.yaml
  - model-cache-pvc.yaml
  - redis-pvc.yaml
  - redis.yaml
  - qdrant.yaml
  - backendconfig.yaml
  - frontend-backendconfig.yaml
  - managed-certificate.yaml
  - frontendconfig.yaml
  - deployment.yaml
  - frontend-deployment.yaml
  - service.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml
