apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backendconfig.yaml
  - managed-certificate.yaml
  - frontendconfig.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
